global.topics = {};

global.topics[$ "Example"] = [
	new SpeakerAction(por_Junjun_default),
	new TextAction("So if this doesn't work"),
	new SpeakerAction(por_Junjun_default),
	new TextAction("I'm gonna cri"),
	new SpeakerAction(por_Junjun_smug),
	new TextAction("oh my gosh look its working"),
	new SpeakerAction(por_Junjun_dire),
	new TextAction("im crying missing my lover i don't have no power for my side forever"),
	new SpeakerAction(por_Junjun_smug),
	new TextAction("AHHAHAAHAHAHAHAHAHAH")
];


global.topics[$ "Intro2"] = [
	new SpeakerAction(por_Bantay),
	new TextAction("Op?"),
	new SpeakerAction(por_Junjun_default),
	new TextAction("I'm going. How much do I pay?"),
	new SpeakerAction(por_Bantay),
	new TextAction("Let's see...your time is.."),
	new SpeakerAction(por_Bantay),
	new TextAction("..."),
	new SpeakerAction(por_Bantay),
	new TextAction("Damn kid you stayed here for 4 hours?"),
	new SpeakerAction(por_Junjun_default),
	new TextAction("Would've stayed longer if my team wasn't so bad.."),
	new SpeakerAction(por_Bantay),
	new TextAction("pffft"),
	new SpeakerAction(por_Bantay),
	new TextAction("Your pay is 40 pesos."),
	new SpeakerAction(por_Junjun_default),
	new TextAction("Here you go.."),
	new SpeakerAction(por_Junjun_default),
	new TextAction("(I hope nanay doesn't notice the 40 pesos missing from her wallet."),
];

global.topics[$ "Intro3"] = [
	new SpeakerAction(por_Junjun_default),
	new TextAction("Home is this way..."),
	new SpeakerAction(por_Junjun_default),
	new TextAction("It's getting really late..."),
	new SpeakerAction(por_Junjun_default),
	new TextAction("I need to hurry home before Nanay kills me."),
];

global.topics[$ "Intro4"] = [
	new SpeakerAction(por_Junjun_default),
	new TextAction("Araguy...I tripped"),
	new SpeakerAction(por_Junjun_default),
	new TextAction("..."),
	new SpeakerAction(por_Junjun_default),
	new TextAction("HUH!?"),
	new SpeakerAction(por_Junjun_default),
	new TextAction("HOW LONG WAS I OUT?"),
	new SpeakerAction(por_Junjun_default),
	new TextAction("..."),
	new SpeakerAction(por_Junjun_default),
	new TextAction("NANAY'S GONNA KILL ME!"),
];

global.topics[$ "Intro5"] = [
	new SpeakerAction(por_Junjun_default),
	new TextAction("(Okay my house is just to the south)"),
];

global.topics[$ "Intro6A"] = [
	new SpeakerAction(por_Junjun_default),
	new TextAction("H-huh?"),
	new SpeakerAction(por_Junjun_default),
	new TextAction("What's that?"),
];

global.topics[$ "Intro6A"] = [
	new SpeakerAction(por_Junjun_default),
	new TextAction("EHHHH!?"),
];

global.topics[$ "Intro7"] = [
	new SpeakerAction(por_Albularyow),
	new TextAction("Hey relax yo. It's me Manong Albularyow"),
	new SpeakerAction(por_Junjun_default),
	new TextAction("H-Huh"),
	new SpeakerAction(por_Albularyow),
	new TextAction("Ok yo... you kinda got yourself into this mess... now you can see the aswang and the aswang can see you...!"),
	new SpeakerAction(por_Junjun_default),
	new TextAction("Look I... I just wanna go home..."),
	new SpeakerAction(por_Junjun_default),
	new TextAction("I just wanna see my m-mom!"),
	new SpeakerAction(por_Junjun_default),
	new TextAction("WAAAAHHH *cries*"),
	new SpeakerAction(por_Albularyow),
	new TextAction("I get it kid but way back to your place is waaay dangerous.."),
	new SpeakerAction(por_Junjun_default),
	new TextAction("T-then how do I get home?"),
	new SpeakerAction(por_Albularyow),
	new TextAction("Okay okay I got it!"),
	new SpeakerAction(por_Albularyow),
	new TextAction("You see one of these? What I used to kill that aswang."),
	new SpeakerAction(por_Junjun_default),
	new TextAction("What's that?"),
	new SpeakerAction(por_Albularyow),
	new TextAction("It's an anting-anting"),
	new SpeakerAction(por_Junjun_default),
	new TextAction("O-oh..."),
	new SpeakerAction(por_Junjun_default),
	new TextAction("Can I have it?"),
	new SpeakerAction(por_Albularyow),
	new TextAction("Now way yo. This is mine.."),
	new SpeakerAction(por_Junjun_default),
	new TextAction("..."),
	new SpeakerAction(por_Albularyow),
	new TextAction("But if you head west from here... There's another one you can find... fo sure"),
	new SpeakerAction(por_Junjun_default),
	new TextAction("Okay?"),
	new SpeakerAction(por_Junjun_default),
	new TextAction("Lead the way then?"),
	new SpeakerAction(por_Albularyow),
	new TextAction("no."),
	new SpeakerAction(por_Junjun_default),
	new TextAction("What?!"),
	new SpeakerAction(por_Albularyow),
	new TextAction("Yes."),
	new SpeakerAction(por_Junjun_default),
	new TextAction("..."),
	new SpeakerAction(por_Albularyow),
	new TextAction("Here I'll give you something to fend yourself with"),
	new SpeakerAction(por_Junjun_default),
	new TextAction("(What's he gonna do with me slipper?)"),
	new SpeakerAction(por_Albularyow),
	new TextAction("KO BU ANGGALI AAHH!"),
	new SpeakerAction(por_Albularyow),
	new TextAction("There kid... your slippers is blessed... It's now anti-aswang."),
	new SpeakerAction(por_Junjun_default),
	new TextAction("Huh... Thanks?"),
	new SpeakerAction(por_Albularyow),
	new TextAction("Now go, shoo."),
];

global.topics[$ "Abby1"] = [
	new SpeakerAction(por_Abby),
	new TextAction("Hey High Five!"),
	new SpeakerAction(por_Junjun_default),
	new TextAction("High Five!"),
	new SpeakerAction(por_Abby),
	new TextAction("Whoops, missed it. my arm broke."),
	new SpeakerAction(por_Junjun_default),
	new TextAction("(I will never give anyone a high five ever again)"),
];

global.topics[$ "Makoy1"] = [
	new SpeakerAction(por_Junjun_default),
	new TextAction("Yo Makoy!"),
	new SpeakerAction(por_Makoy),
	new TextAction("Junjun! Wanna play some Ins?"),
	new SpeakerAction(por_Junjun_default),
	new TextAction("Ins? of course I wanna play!"),
	new SpeakerAction(por_Junjun_default),
	new TextAction("but with who?"),
	new SpeakerAction(por_Makoy),
	new TextAction("Let's see.."),
	new SpeakerAction(por_Junjun_default),
	new TextAction("(Makoy its in the middle of the day, non plays around this time)"),
	new SpeakerAction(por_Makoy),
	new TextAction("Huh, no one's here"),
	new SpeakerAction(por_Junjun_default),
	new TextAction("Maybe next time.."),
];